# Generated by Django 5.1.7 on 2025-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_app", "0002_alter_clientproducts_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQS",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
    ]
